/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 C:\Users\fgarr\Documents\lab\Granity\packages\engine\public\Toilet.gltf --transform
*/

import { useGLTF } from "@granity/three/drei";
import { useRef } from "react";

export function Toilet(props: any) {
    const { nodes, materials } = useGLTF("/assets/Toilet-transformed.glb") as any;
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Cylinder001.geometry}
                material={materials["Material #25"]}
                position={[-9, 0, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
                geometry={nodes.Box001.geometry}
                material={materials["Material #25"]}
                position={[-3.83, 90.07, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
                geometry={nodes.Box002.geometry}
                material={materials["Material #25"]}
                position={[-71.35, 153, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
            />
        </group>
    );
}

useGLTF.preload("/assets/Toilet-transformed.glb");
